# Generated by Django 5.0.6 on 2024-06-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('brief_description', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about_us_images/')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
